### PR TITLE
Fix4K and Resizer

### PR DESCRIPTION
**Pull request by JulianPaoloThiry**
Two new plugins in the new 1.0.0 framework.

### CODE REVIEW

**Comment by eltorqiro** [comment]
Excellent work adapting that so quickly!  You beat me to it :)

I'm tied up today, but will look at getting this in tomorrow.  Cheers.

**Comment by JulianPaoloThiry** [comment]
Found a couple of unexpected bugs that had to be fixed.

**Comment by eltorqiro** [comment]
I've squash merged this into the develop branch.  I should have specified earlier that I use a gitflow-style workflow for branches.  For future updates, please create a branch off develop, make your changes, then squash merge them back into develop and do the pull request for that.

If you'd prefer to do that for this particular one, I can undo the commit and you can resubmit, it's up to you.

Have to say, I'm mightily impressed at how you put all that together with virtually no documentation.  Really nice work figuring out the framework, and then re-figuring it out for 1.x :)

**Comment by eltorqiro** [comment]
Also, since you know what you're doing I am happy to make you an author on the project here on github.  So that's another way we can go if you prefer.

**Comment by eltorqiro** [comment]
Ahh, I just noticed that Resize Windows applies scale when you drag the sliders, regardless whether the plugin is enabled or not, due to the prefChangeHandler.  I've fixed it, check ca89c29

Hope you're ok with me doing this, we should sort out some sort of boundaries as to what is acceptable and what isn't.  I don't want to annoy you by making changes like this.

**Comment by eltorqiro** [comment]
I've got some other fixes I want to put out for other plugins, so I am going to go ahead and publish today.  We should chat though, as I don't want to annoy you with the change I made to Resizer, and would like to sort out how we will tackle future updates.  Very keen to keep you happy with it and make sure you aren't left feeling like I'm hijacking your plugins.

**Pull request closed without merging**
